### ISSUE TITLE
Not work when I delete assets.

### ISSUE THREAD

**Issue by jinyoungbaek98** [Ryan-DowlingSoka/ImporterRules#1]
Hello!

Recently I saw the notGDC page and I'm so interested in this plugin.

I made interchange pipeline by scripting in Python.
I use this plugin. → just add import rules(like setting properties)

I made some rules and put in startup script. When I open editor first time, Everything works very well. Import setting works perfect. 
But after I delete something(assets) it doesn’t work.

I can’t see any python logs and import setting sets default value.
I have no idea with this problem.

Sorry for my poor English. Thank you

**Comment by Ryan-DowlingSoka** [comment]
I think I've seen something like this before. After a delete I think it might clear the delegates in python. You may need to reapply them.

Try running the startup script again, if that works then it is that the delegates are getting cleared.

I'm not sure the best way to fix right now, but it could be a good starting point.

**Comment by jinyoungbaek98** [comment]
Thanks for your answer.

Actually, I tried to reapply startup script before. But it doesn't work.😂
I think script related in interchange pipelines or import settings will be applied when opening editor.

If I can't resolve this problem, then using c++ plugin instead.
Thank you

**Comment by jinyoungbaek98** [comment]
Finally, I found it.
I'm not sure why it's causing the problem like this. But it worked well.

![캡처](https://github.com/Ryan-DowlingSoka/UnrealImporterRules-Python/assets/155529819/e46af567-fb3c-4c00-9aff-166a8f92cec6)
In 'Manager.py' import_subsystem is just declared in local variable. I just change it to member variable by adding 'self.'.
Then it works! I think it was problem of memory.(just my opinion. I'm not good at Python)

I leave this comment because I think you might be curious. 
I can't say this is the right answer, but I wanted to let you know ;)

**Comment by Ryan-DowlingSoka** [comment]
Yes! That does look like it would cause the issue. I'll make the fix.
